language: rust
sudo: false
rust: stable

env:
  global:
    - PROJECT_NAME=rubigo
    - FILE_NAME=${PROJECT_NAME}-${TRAVIS_OS_NAME}-64bit.tar.gz

script:
  - cargo test -- --nocapture
  - cargo build --release

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OPENSSL_LIB_DIR=`brew --prefix openssl`/lib; fi

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

branches:
  only:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    - master

before_deploy:
  - strip "target/release/${PROJECT_NAME}"
  - tar czf "${FILE_NAME}" -C target/release "${PROJECT_NAME}"

deploy:
  provider: releases
  api_key:
    secure: L07pFDLCtsmv5/RNkSmqeMoR2DbCB2h+7QsNrRAllw3gSmcW2stXG1w2tuUTRKE0+pOE0fau2hiVReBagYS3yof1k2ksxCJhUad99LUzFJmxYkTvVwHfmkeoqUi2WD10+DEsI4z5UZ69/F7cnBNlsJ6k8PKq6q0JS7Ob477Ga4Dd5QMmKEZVt2k0eSyn99TLzSas/DLNttwlGSkubkxL1oTdDyq2NVlX7kCuYAfKBbCMDpmkCuq4BQUOaTACHcYP3YaDiI/NOUeMMNIb8EV9R50PPXb2k9aV37GreSpw/9hDKBQ/plgTmHXf0cNKOSBoQ2qsVgrPBxfzUNAJXwlWRDgiqac2ct+0EcEA6DCoO7E7RzRD7f2VHl0vYuW1wPoR8aTq0IXVMq2+w8rfuH7FXwg9mgDfeSDrGANUZslSWdTzJRmKQMgtmTAQIJeJZGRGidOx73NoOUMpWeqWdAEM74jATHVzqghYX/Homp4n1PDpZ5M8jG0OffUBvj/Zop2hwnFxE7KtTsO5+ZTNmd8UEk7DlNN4QEWeea3ae/+95IzBjwR8UlIi60NMK5cJPSNm1+U2zbDR8rteAonm4xKSHS1v5BxPYQDsb4jS97Uux6jDXhKLf87Pl2dHtZHdhEFwcF64nMhDiaGrVZKii59U6oGlYs5179jQu9zxbB7ZXYo=
  file: "${FILE_NAME}"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
