[package]
name = "rubigo"
version = "0.1.0"
authors = ["Navid <yaa110@gmail.com>"]

[dependencies]
ansi_term = "0.9"
git2 = "0.6"
json = "0.11"
clap = "2.23"
time = "0.1"
threadpool = "1.3"
num_cpus = "1.0"
futures = "0.1"
futures-cpupool = "0.1"
semver = "0.6.0"
