[package]
name = "rubigo"
version = "0.1.0"
authors = ["Navid <yaa110@gmail.com>"]

[dependencies]
ansi_term = "0.9.0"
git2 = "0.6"
json = "0.11.6"
clap = "2.22.2"
time = "0.1.36"
threadpool = "1.0"
num_cpus = "1.0"
